### ISSUE TITLE
Missing latest Linux builds

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/luigi-feedstock#6]
The build completed but no file was uploaded. Same as https://github.com/conda-forge/nco-feedstock/issues/15 and https://github.com/conda-forge/erlang-feedstock/issues/1

**Comment by jakirkham** [comment]
Based on the CircleCI history it doesn't seem the last build for `master` was ever run. Going to try restarting.

**Comment by jakirkham** [comment]
Have successfully gotten CircleCI to start a [build]( https://circleci.com/gh/conda-forge/luigi-feedstock/12 ). Please keep an eye on whether this uploads the binaries or not. FWIW this issue seems to be different from `erlang`. Not sure what the issue is with `nco`.

**Comment by jakirkham** [comment]
Also should add this was not a failed webhook delivery to CircleCI. There was simply no delivery whatsoever.

**Comment by jakirkham** [comment]
Wow that build is fast. Appears all the 2.2.0 releases are up for Linux. Going to go ahead and close. Feel free to let me know if there is still something wrong.
